version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: extrahours-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: extrahoursdb
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - extrahours-net

  backend:
    build:
      context: .  # Raíz del proyecto
      dockerfile: ExtraHours.API/Dockerfile  # Dockerfile dentro de la carpeta del backend
    container_name: extrahours-backend
    depends_on:
      - mysql
    ports:
      - "5023:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: server=extrahours-mysql;port=3306;database=extrahoursdb;user=user;password=user123;
      Jwt__Key: 1234567890123456789012345678901thisIsASecureJwtKeyWithMoreThan32Chars!!
      Jwt__Issuer: http://localhost:5023
      Jwt__Audience: http://localhost:5173
     # Asegura que el .dll se ejecute desde su carpeta
    networks:
      - extrahours-net

  frontend:
    build:
      context: ./fronted  # carpeta del frontend
    container_name: extrahours-frontend
    ports:
      - "5173:80"
    environment:
      VITE_API_BASE_URL: http://backend:5023/api
      
    depends_on:
      - backend
    networks:
      - extrahours-net

volumes:
  mysql_data:

networks:
  extrahours-net:
